### ISSUE TITLE
Rultor release

### ISSUE THREAD

**Issue by l3r8yJ** [volodya-lombrozo/jtcop#77]
As far as I understand, `@rultro release` is not installed in this project, if so this [post](https://www.l3r8y.ru/2023/03/19/how-to-deploy-with-rultor-and-not-shoot-yourself-in-the-foot) might be useful

**Comment by volodya-lombrozo** [comment]
@l3r8yJ, I don't trust Rultor to release packages since I have to send my credentials to it. Therefore, I decided to release packages only using GitHub actions. Here's how it works:

- I request Rultor to release the package
- Rultor performs a simple build
- Then Rultor publishes the release on GitHub (if build is successful)
- Then the release pipeline (GitHub actions) takes over and begins the release process.

You can check it [here](https://github.com/volodya-lombrozo/jtcop/blob/main/.github/workflows/maven.release.yml).

**Comment by l3r8yJ** [comment]
@volodya-lombrozo maybe we can suggest a more private way of releasing for Rultor via issue, what do you think?

**Comment by volodya-lombrozo** [comment]
@l3r8yJ To be honest, I don't like the idea of building something inside Rultor at all, because Rultor obviously is not so powerful  comparing with GitHub actions. For example, using GitHub actions, we can check our build for many different platforms at once (windows, Mac, linux) rather than Rultor that uses only one selected platform (it's a Linux by default). I'm personally use Rultor as helpful assistant that can check a build one more time and can publish releases. 

I've asked similar question [here](https://github.com/yegor256/rultor/issues/1565).

As for security - I just don't know how else we can guaranty security in that case (in any case you have to share your credentials with Rultor). But if you want, you can ask question or send an issue to Rultor repo. I believe it would be interesting to figure out.

**Comment by l3r8yJ** [comment]
@volodya-lombrozo understand you, it is really hard to make it more private with the sharing of credentials
